[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# We don't need the Next.js plugin for static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
